const $ = (s) => document.querySelector(s);
const roleSelect=$('#roleSelect');const leadList=$('#leadList');const workbenchPage=$('#workbenchPage');
function setRole(role){const admin=role==='admin';leadList.classList.toggle('hidden',!admin);workbenchPage.classList.toggle('hidden',admin);document.querySelector('.admin-nav').classList.toggle('hidden',!admin);}
roleSelect.addEventListener('change',e=>setRole(e.target.value));
document.querySelectorAll('[data-open-workbench]').forEach(btn=>btn.addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');showToast('已进入 Sofia Ramirez 的销售工作台');}));
$('#openSalesWorkbench').addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');});
setRole('sales');
const tabs = document.querySelectorAll('.tab');
tabs.forEach(tab => tab.addEventListener('click', () => {
  tabs.forEach(t => t.classList.remove('active'));
  tab.classList.add('active');
  $('#opsPanel').classList.toggle('hidden', tab.dataset.tab !== 'ops');
  $('#notesPanel').classList.toggle('hidden', tab.dataset.tab !== 'notes');
}));

const leadStates = {
  pending:{main:'待跟进',sub:'—',progress:'20%',count:'1 / 5 阶段',items:[['未接通','自动联系','第2次 +2小时','状态 → 跟进中 · 已联系；跟进次数 +1'],['已沟通-有意向','确认意向车型','承诺时间或 +2小时 / 次日10:00','确认意向车型，进入购车引导'],['已沟通-无意向','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 无意向购买'],['要求稍后联系','按客户指定时间回访','销售录入客户指定时间','状态 → 跟进中 · 已联系'],['号码错误','无动作（终态）','—','状态 → 战败-号码错误'],['已发送预审链接','跟进预审进度','第2次 +2小时；第3次次日10:00','状态 → 跟进中 · 已联系']]},
  following:{main:'跟进中',sub:'已联系',progress:'40%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系状态流转','按联系节奏','状态保持 跟进中 · 已联系'],['已发送预审链接','跟进预审进度','第2次 +2小时；第3次次日10:00','直接触发复制链接动作'],['试驾','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 试驾'],['已沟通-无意向','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 无意向购买'],['未接通（第2次）','重新联系','第3次次日10:00','状态不变；跟进次数 +1（累计2）'],['未接通（第3次，达上限）','无动作','—','系统自动 → 战败（原因：未接通）'],['要求稍后联系','按客户指定时间回访','销售录入客户指定时间','状态不变'],['预审通过','进入订单流程','—','状态 → 订单中-预审通过'],['放弃购买','无动作（终态）','—','状态 → 战败（原因：暂时不买）']]},
  order:{main:'订单中',sub:'预审通过',progress:'70%',count:'4 / 5 阶段',items:[['待客户进件','联系用户，提醒协助提交进件材料','预审通过后+2小时；先+1天、+3天','状态保持 订单中'],['等待信审结果','主动查询订单状态','+1 / +3 / +7天','状态保持 订单中'],['报价待确认','推动客户确认金融报价方案','进入后+1天首跟，未完成每+1天','状态保持 订单中'],['合同待签署','协助客户确认/签署合同','进入后+1天首跟，未完成每+1天','状态保持 订单中'],['等待放款','跟进放款进度，需找 Mstar 查询','进入后+1天首跟，未完成每+1天','状态保持 订单中']]},
  testdrive:{main:'暂存',sub:'试驾',progress:'45%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  cash:{main:'暂存',sub:'确认全款',progress:'55%',count:'3 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（未达上限）','重新联系','第2次 +2小时；第3次次日10:00','状态不变；重试次数 +1'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  'no-intent':{main:'暂存',sub:'无意向购买',progress:'35%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（未达上限）','重新联系','第2次 +2小时；第3次次日10:00','状态不变；重试次数 +1'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  lost:{main:'战败',sub:'—',progress:'100%',count:'终态',items:[['战败','无后续动作','—','原因：号码错误 / 放弃购买 / 预审失败 / 未接通电话']]}
};
function renderLeadState(key){
  const data=leadStates[key]; $('#currentMainState').textContent=data.main; $('#currentSubState').textContent=data.sub; $('#lostReasonWrap').classList.toggle('hidden', key !== 'lost');
  const list=$('#stageList'); list.innerHTML=data.items.map((x,i)=>`<button class="stage ${i===0?'selected':''}" data-stage="${x[0]}" data-action="${x[3]}" data-next="${x[2]}"><span class="stage-radio"></span><b>${x[0]}</b><small>${x[1]}</small><time>${x[2]}</time></button>`).join(''); bindStages(); const first=data.items[0]; $('#autoAction').textContent=first[3]; $('#nextAction').textContent=first[2];
}
function bindStages(){document.querySelectorAll('.stage').forEach(stage=>stage.addEventListener('click',()=>{document.querySelectorAll('.stage').forEach(s=>s.classList.remove('selected'));stage.classList.add('selected');$('#autoAction').textContent=stage.dataset.action;$('#nextAction').textContent=stage.dataset.next;}));}
$('#leadStateSelect').addEventListener('change',e=>renderLeadState(e.target.value)); $('#leadStateSelect').value='following'; renderLeadState('following');
document.querySelector('.identity-card .text-btn').addEventListener('click',()=>$('#userInfoModal').classList.remove('hidden'));
$('#closeUserModal').addEventListener('click',()=>$('#userInfoModal').classList.add('hidden'));
document.querySelectorAll('.info-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.info-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');['current','original','history'].forEach(k=>$('#'+k+'InfoPanel').classList.toggle('hidden',k!==tab.dataset.infoTab));}));
$('#saveUserInfo').addEventListener('click',()=>{const map={currentLeadType:$('#editType').value,currentPhone:$('#editPhone').value,currentBrand:$('#editBrand').value,currentSeries:$('#editSeries').value,currentModel:$('#editModel').value,currentDealer:$('#editDealer').value,currentAddress:$('#editAddress').value,currentRegion:$('#editRegion').value};Object.entries(map).forEach(([id,value])=>$('#'+id).textContent=value||'—');const reason=$('#editReason').value.trim()||'销售手动更新用户信息';$('#changeList').innerHTML=`<div class="change-item"><time>刚刚 · Sofia Ramirez</time><p>${escapeHtml(reason)}</p><small>当前信息已更新，原始线索快照保持不变</small></div>`;$('#userInfoModal').classList.add('hidden');showToast('当前用户信息已保存，原始信息已保留');});

$('#addNoteBtn').addEventListener('click', () => { $('#noteForm').classList.remove('hidden'); $('#noteInput').focus(); });
$('#cancelNote').addEventListener('click', () => { $('#noteForm').classList.add('hidden'); $('#noteInput').value = ''; });
$('#noteForm').addEventListener('submit', (e) => {
  e.preventDefault();
  const text = $('#noteInput').value.trim(); if (!text) return;
  const item = document.createElement('div'); item.className = 'timeline-item';
  item.innerHTML = `<span class="timeline-dot purple"></span><div><div class="timeline-head"><time>刚刚</time></div><p>${escapeHtml(text)}</p><div class="operator-line">操作人：sales 001 Deng Yao</div></div>`;
  $('#noteTimeline').prepend(item); $('#noteForm').classList.add('hidden'); $('#noteInput').value = '';
  $('#noteCount').textContent = Number($('#noteCount').textContent) + 1; showToast('跟踪记事已保存');
});
$('#precheckBtn').addEventListener('click', () => $('#precheckModal').classList.remove('hidden'));
$('#closePrecheck').addEventListener('click', () => $('#precheckModal').classList.add('hidden'));
$('#precheckModal').addEventListener('click', e => { if(e.target.id === 'precheckModal') e.currentTarget.classList.add('hidden'); });
$('#savePrecheck').addEventListener('click', () => showToast('预审信息已保存'));
$('#startAttribution').addEventListener('click', () => showToast('归因链接已发起'));
$('#favoriteBtn').addEventListener('click', () => { const b = $('#favoriteBtn'); b.classList.toggle('active'); b.textContent = b.classList.contains('active') ? '★ 已收藏' : '☆ 收藏'; showToast(b.classList.contains('active') ? '已加入收藏' : '已取消收藏'); });
const leadQueue=[{name:'Sofia Ramirez',phone:'5899022435',main:'跟进中',sub:'已联系',state:'following',brand:'长安',series:'CS75 PLUS',model:'1.5T 尊贵型',notes:['客户希望了解月供方案，已发送车型与金融政策资料。','已通过 WhatsApp 发送问候，等待客户回复。']},{name:'David Chen',phone:'5612345454',main:'待跟进',sub:'—',state:'pending',brand:'NISSAN',series:'MAGNITE',model:'Exclusive MT',notes:['首次线索进入，待销售首次联系。']},{name:'María López',phone:'5588123344',main:'订单中',sub:'预审通过',state:'order',brand:'长安',series:'UNI-K',model:'2.0T 尊贵型',notes:['预审已通过，等待客户提交进件材料。','已向客户说明下一步签约流程。']},{name:'Carlos Ruiz',phone:'5510027811',main:'暂存',sub:'试驾',state:'testdrive',brand:'长安',series:'CS75 PLUS',model:'2.0T 旗舰型',notes:['客户希望周末到店试驾。']},{name:'Ana Torres',phone:'5549081266',main:'暂存',sub:'确认全款',state:'cash',brand:'FORD',series:'Explorer',model:'Advance 2 Row',notes:['客户确认全款购买，等待确认车辆库存。']},{name:'Luis Hernández',phone:'5532219088',main:'暂存',sub:'无意向购买',state:'no-intent',brand:'MAZDA',series:'CX-30',model:'尊贵型',notes:['客户暂时没有购车计划，30天后再唤醒。']},{name:'Jorge Morales',phone:'5521807766',main:'战败',sub:'—',state:'lost',brand:'—',series:'—',model:'—',notes:['号码错误，系统已终止后续跟进。']}];let currentLeadIndex=0;
function renderLeadActivity(lead){$('#currentName').textContent=lead.name;$('#currentPhone').textContent=lead.phone;$('#currentBrand').textContent=lead.brand;$('#currentSeries').textContent=lead.series;$('#currentModel').textContent=lead.model;$('#opsTimeline').innerHTML=`<div class="timeline-item"><span class="timeline-dot gray"></span><div><div class="timeline-head"><b>进入当前工作台</b><time>刚刚</time></div><p>系统根据销售提交结果切换到下一条线索</p><div class="operator-line">操作人：系统</div></div></div><div class="timeline-item"><span class="timeline-dot blue"></span><div><div class="timeline-head"><b>线索已创建</b><time>今天 09:30</time></div><p>来源：系统自动 · 线索中心</p><div class="operator-line">操作人：系统</div></div></div>`;$('#noteTimeline').innerHTML=lead.notes.map((n,i)=>`<div class="timeline-item"><span class="timeline-dot purple"></span><div><div class="timeline-head"><time>${i?'昨天 16:40':'今天 10:18'}</time></div><p>${escapeHtml(n)}</p><div class="operator-line">操作人：sales 001 Deng Yao</div></div></div>`).join('');$('#noteCount').textContent=lead.notes.length;}
function loadNextLead(){currentLeadIndex=(currentLeadIndex+1)%leadQueue.length;const lead=leadQueue[currentLeadIndex];$('#leadStateSelect').value=lead.state;renderLeadState(lead.state);$('#currentMainState').textContent=lead.main;$('#currentSubState').textContent=lead.sub;renderLeadActivity(lead);showToast(`已提交，进入下一条：${lead.name}`);}
$('#completeBtn').addEventListener('click', () => { if(!$('#lostReasonWrap').classList.contains('hidden') && !$('#lostReason').value){ showToast('请先选择战败原因'); $('#lostReason').focus(); return; } loadNextLead(); });
const allLeadRows=[['跟进中','已联系','Sofia Ramirez','5899022435','长安','CS75 PLUS','WhatsApp'],['待跟进','—','David Chen','5612345454','NISSAN','MAGNITE','车辆页'],['订单中','预审通过','María López','5588123344','长安','UNI-K','金融机构'],['暂存','试驾','Carlos Ruiz','5510027811','长安','CS75 PLUS','试驾活动'],['暂存','确认全款','Ana Torres','5549081266','FORD','Explorer','门店录入'],['暂存','无意向购买','Luis Hernández','5532219088','MAZDA','CX-30','销售跟进'],['战败','号码错误','Jorge Morales','5521807766','—','—','系统自动'],['待跟进','要求稍后联系','Elena García','5577331188','NISSAN','X-TRAIL','官网表单'],['跟进中','已发送预审链接','Miguel Soto','5566012331','长安','逸动','金融机构'],['订单中','等待信审结果','Paola Cruz','5598802211','长安','UNI-V','销售跟进'],['暂存','未接通（达上限）','Rafael Díaz','5511907722','—','—','系统自动'],['战败','放弃购买','Lucía Vega','5544076110','—','—','销售跟进']];
document.querySelector('.lead-table tbody').innerHTML=allLeadRows.map(r=>`<tr><td><span class="table-pill">${r[0]}</span></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>2026-08-05 06:42</td><td>${r[6]}</td><td><button class="table-link" data-open-workbench>查看</button></td></tr>`).join('');document.querySelectorAll('[data-open-workbench]').forEach(btn=>btn.addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');showToast('已进入对应销售工作台');}));
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
$('#changeList').innerHTML='<div class="change-item"><time>今天 10:18 · Sofia Ramirez</time><p><b>车型</b>：3 Sedan → I GRAND TOURING MHEV TA</p><small>修改原因：客户电话确认最终意向车型</small></div><div class="change-item"><time>昨天 16:42 · Sofia Ramirez</time><p><b>地址</b>：Av. Vallarta 1200 → Av. Vallarta 1410</p><small>修改原因：客户补充完整门牌号</small></div><div class="change-item"><time>07-21 11:05 · 系统同步</time><p><b>地区</b>：Ciudad de México → Ciudad de México · CDMX</p><small>修改原因：根据经销商区域信息自动补全</small></div>';
const currentDemo={currentLeadType:'全款',currentPhone:'5899022435',currentBrand:'长安',currentSeries:'CS75 PLUS',currentModel:'1.5T 尊贵型',currentDealer:'Changan Polanco Centro',currentAddress:'Av. Vallarta 1410',currentRegion:'Guadalajara · JAL'};Object.entries(currentDemo).forEach(([id,value])=>{const el=$('#'+id);if(el)el.textContent=value;});const editDemo={editType:'全款',editPhone:'5899022435',editBrand:'长安',editSeries:'CS75 PLUS',editModel:'1.5T 尊贵型',editDealer:'Changan Polanco Centro',editAddress:'Av. Vallarta 1410',editRegion:'Guadalajara · JAL'};Object.entries(editDemo).forEach(([id,value])=>{const el=$('#'+id);if(el)el.value=value;});
document.querySelectorAll('.note-meta span:first-child').forEach(el=>{el.textContent='操作人：sales 001 Deng Yao';});
