const $ = (s) => document.querySelector(s);
const roleSelect=$('#roleSelect');const leadList=$('#leadList');const workbenchPage=$('#workbenchPage');const moduleView=$('#moduleView');
const tenantSelect=$('#tenantSelect');tenantSelect.addEventListener('change',e=>{const tenant=e.target.value==='baic'?'北汽 · 合作主机厂':'AutoCava · 平台';document.querySelector('.crumbs').innerHTML=`${tenant} <span>/</span> 线索中心 <span>/</span> 权限范围内数据`;showToast(`已切换租户：${tenant}`);});
let menuConfig=[];
function renderMenus(role){const nav=document.querySelector('.admin-nav');const visible=menuConfig.filter(m=>m.enabled&&m.roles.includes(role));nav.innerHTML=visible.map(m=>`<button data-module="${m.key}">${m.name}</button>`).join('');nav.querySelectorAll('[data-module]').forEach(btn=>btn.addEventListener('click',()=>showModule(btn.dataset.module)));}
fetch('./menus.json').then(r=>r.json()).then(data=>{menuConfig=data;renderMenus(roleSelect.value);}).catch(()=>showToast('菜单配置加载失败，请确认 menus.json 已上传'));
function setRole(role){const admin=role==='admin'||role==='tenant_admin';leadList.classList.toggle('hidden',!admin);workbenchPage.classList.toggle('hidden',admin);moduleView.classList.toggle('hidden',!admin);document.querySelector('.admin-nav').classList.toggle('hidden',!admin);renderMenus(role);if(admin)showModule('leads');}
roleSelect.addEventListener('change',e=>setRole(e.target.value));
document.querySelectorAll('[data-open-workbench]').forEach(btn=>btn.addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');showToast('已进入 Sofia Ramirez 的销售工作台');}));
$('#openSalesWorkbench').addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');});
setRole('sales');
const moduleTemplates={dashboard:`<div class="module-head"><div><div class="eyebrow">CRM OVERVIEW</div><h1>后台总览</h1><p>今日销售任务、线索转化和订单协同概览</p></div></div><div class="stat-grid"><div class="stat-card"><span>今日待处理任务</span><b>18</b><small>较昨日 +4</small></div><div class="stat-card"><span>即将到期</span><b class="warn">6</b><small>未来 2 小时内</small></div><div class="stat-card"><span>已完成任务</span><b>42</b><small>完成率 78%</small></div><div class="stat-card"><span>订单跟进中</span><b>27</b><small>需要销售关注</small></div></div><div class="module-grid"><div class="module-card"><h2>今日任务分布</h2><div class="bar-row"><span>首次联系</span><i style="width:72%"></i><b>8</b></div><div class="bar-row"><span>回访任务</span><i style="width:54%"></i><b>6</b></div><div class="bar-row"><span>预审推进</span><i style="width:32%"></i><b>3</b></div><div class="bar-row"><span>订单跟进</span><i style="width:18%"></i><b>1</b></div></div><div class="module-card"><h2>需要关注</h2><div class="alert-row"><span class="dot red"></span><div><b>6 条任务即将到期</b><small>最早截止：今天 14:30</small></div></div><div class="alert-row"><span class="dot amber"></span><div><b>3 条订单状态超过 24 小时未更新</b><small>需要创建下游协同任务</small></div></div></div></div>`,
tasks:`<div class="module-head"><div><div class="eyebrow">TASK CENTER</div><h1>销售任务中心</h1><p>按任务状态和截止时间管理销售工作</p></div><button class="primary small">+ 手动创建任务</button></div><div class="task-tabs"><button class="active">我的任务 <b>18</b></button><button>即将到期 <b>6</b></button><button>已逾期 <b>2</b></button><button>已完成</button></div><div class="task-table module-card"><div class="task-row task-header"><span>任务</span><span>关联线索</span><span>分类</span><span>联系对象</span><span>截止时间</span><span>状态</span><span>操作</span></div>${[['预审回访','Sofia Ramirez','用户提醒任务','用户','今天 15:30','待处理'],['未接通重试','David Chen','用户提醒任务','用户','今天 16:00','待处理'],['合同生成超时','María López','下游协同任务','金融机构运营','已逾期 2 小时','逾期'],['订单状态回访','Carlos Ruiz','状态告知任务','用户','明天 10:00','待处理']].map(r=>`<div class="task-row"><span><b>${r[0]}</b><small>回访任务</small></span><span>${r[1]}</span><span>${r[2]}</span><span>${r[3]}</span><span>${r[4]}</span><span class="status-chip">${r[5]}</span><button class="table-link">进入处理</button></div>`).join('')}</div>`,
preapproval:`<div class="module-head"><div><div class="eyebrow">PREAPPROVAL</div><h1>预审推进</h1><p>按预审节点查看用户待完成动作和销售任务</p></div></div><div class="stage-cards"><div><span>未开始</span><b>12</b><small>愿意预审但尚未进入</small></div><div><span>填写中</span><b>8</b><small>已填写部分信息</small></div><div><span>待验证</span><b>5</b><small>手机或授权未完成</small></div><div><span>提交失败</span><b>2</b><small>需要重新引导提交</small></div></div><div class="module-card"><h2>预审任务</h2><div class="task-row task-header"><span>用户</span><span>当前节点</span><span>销售动作</span><span>截止时间</span><span>状态</span></div><div class="task-row"><span>Sofia Ramirez</span><span>已发送链接未进入</span><span>提醒进入预审</span><span>今天 15:30</span><span class="status-chip">待处理</span></div><div class="task-row"><span>David Chen</span><span>手机验证未完成</span><span>提醒完成手机验证</span><span>今天 17:00</span><span class="status-chip">待处理</span></div></div>`,
orders:`<div class="module-head"><div><div class="eyebrow">ORDER FOLLOW-UP</div><h1>订单跟进</h1><p>订单状态由下游系统回传，销售只处理对应任务</p></div></div><div class="sub-nav"><button class="active">订单状态</button><button>用户待办 <b>9</b></button><button>下游协同 <b>3</b></button></div><div class="module-card"><div class="task-row task-header"><span>用户</span><span>订单状态</span><span>停留时长</span><span>销售任务</span><span>数据来源</span><span>操作</span></div>${[['María López','预审通过','2 小时','待客户进件','Mstar'],['Paola Cruz','等待信审结果','26 小时','告知订单状态','Mstar'],['Carlos Ruiz','合同待签署','31 小时','提醒用户签署合同 / 下游协同','Mstar']].map(r=>`<div class="task-row"><span>${r[0]}</span><span><b>${r[1]}</b></span><span>${r[2]}</span><span>${r[3]}</span><span>${r[4]}</span><button class="table-link">查看</button></div>`).join('')}</div>`,
records:`<div class="module-head"><div><div class="eyebrow">AUDIT CENTER</div><h1>记录中心</h1><p>统一查询系统操作、跟踪记事和信息变更</p></div></div><div class="sub-nav"><button class="active">操作记录</button><button>跟踪记事</button><button>信息变更记录</button></div><div class="module-card"><div class="record-line"><time>今天 10:35</time><b>跟进阶段更新为「未接通」</b><span>操作人：系统</span></div><div class="record-line"><time>今天 10:34</time><b>销售手动修改用户信息</b><span>操作人：sales 001 Deng Yao</span></div><div class="record-line"><time>今天 10:18</time><b>客户对 CS75 PLUS 有兴趣</b><span>操作人：sales 001 Deng Yao</span></div></div>`,
config:`<div class="module-head"><div><div class="eyebrow">TASK CONFIGURATION</div><h1>任务体系配置</h1><p>配置任务分类、触发规则、联系人和完成标准</p></div><button class="primary small">+ 新建任务规则</button></div><div class="config-layout"><div class="config-menu"><button class="active">全部任务规则</button><button>首次联系任务</button><button>回访任务</button><button>预审推进任务</button><button>订单状态跟进</button></div><div class="module-card config-list"><div class="config-row config-header"><span>任务子类型</span><span>任务分类</span><span>联系对象</span><span>触发规则</span><span>状态</span></div>${[['FIRST_CONTACT','用户提醒任务','用户','线索创建 / 首次分配','启用'],['RETRY_CONTACT','用户提醒任务','用户','未接通 +2小时','启用'],['FOLLOW_PREAPPROVAL_PROGRESS','用户提醒任务','用户','预审节点变化','启用'],['FOLLOW_ORDER_TIMEOUT','下游协同任务','下游运营','订单状态超时','启用']].map(r=>`<div class="config-row"><span><b>${r[0]}</b></span><span>${r[1]}</span><span>${r[2]}</span><span>${r[3]}</span><span class="status-chip">${r[4]}</span></div>`).join('')}</div></div>`};
function showModule(key){const isLeads=key==='leads';leadList.classList.toggle('hidden',!isLeads);moduleView.classList.toggle('hidden',isLeads);workbenchPage.classList.add('hidden');if(!isLeads)moduleView.innerHTML=moduleTemplates[key]||'';if(key==='config')moduleView.insertAdjacentHTML('afterbegin','<div class="tenant-scope"><b>当前配置范围</b><span>租户：北汽 · 合作主机厂</span><span>品牌：北汽</span><span>当前生效版本：V2</span><span class="status-chip">已发布</span></div>');document.querySelectorAll('.admin-nav [data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module===key));}
document.querySelectorAll('.admin-nav [data-module]').forEach(btn=>btn.addEventListener('click',()=>showModule(btn.dataset.module)));
const tabs = document.querySelectorAll('.tab');
tabs.forEach(tab => tab.addEventListener('click', () => {
  tabs.forEach(t => t.classList.remove('active'));
  tab.classList.add('active');
  $('#opsPanel').classList.toggle('hidden', tab.dataset.tab !== 'ops');
  $('#notesPanel').classList.toggle('hidden', tab.dataset.tab !== 'notes');
}));
const taskByState={pending:{title:'首次联系',summary:'完成首次有效联系，确认购车意向、金融意向和下一步动作',type:'用户提醒任务',target:'用户',group:'首次联系任务',completion:'完成一次有效联系并记录跟进结果'},following:{title:'回访任务',summary:'联系用户确认最新意向，并确定下一步动作',type:'用户提醒任务',target:'用户',group:'回访任务',completion:'完成联系并记录用户反馈，或重新约定时间'},order:{title:'订单状态回访',summary:'告知用户预审通过进度，确认是否收到下游通知',type:'状态告知任务',target:'用户',group:'订单状态跟进任务',completion:'告知当前状态并记录用户是否理解下一步'},testdrive:{title:'试驾回访',summary:'确认试驾安排与客户反馈，必要时重新约定时间',type:'用户提醒任务',target:'用户',group:'回访任务',completion:'记录试驾反馈并设置下一次跟进时间'},cash:{title:'用户提醒任务',summary:'提醒用户确认全款购车安排和车辆库存',type:'用户提醒任务',target:'用户',group:'订单状态跟进任务',completion:'确认用户收到通知并记录反馈'},'no-intent':{title:'沉默回捞',summary:'到达回捞时间后重新确认用户购车意向',type:'用户提醒任务',target:'用户',group:'回访任务',completion:'完成联系并记录新的意向结果'},lost:{title:'战败归档',summary:'该线索已进入终态，不再生成销售任务',type:'纯等待',target:'—',group:'—',completion:'无需跟进'}};
function updateTaskContext(key){const t=taskByState[key]||taskByState.following;$('#taskTitle').textContent=t.title;$('#taskSummary').textContent=t.summary;$('#taskType').textContent=t.type;$('#contactTarget').textContent=t.target;$('#taskGroup').textContent=t.group;$('#taskCompletion').textContent=t.completion;$('#taskDue').textContent=key==='lost'?'—':key==='order'?'明天 10:00':'今天 15:30';}
$('#taskCenterBtn').addEventListener('click',()=>showToast('我的任务：1 条待处理，2 条即将到期'));

const leadStates = {
  pending:{main:'待跟进',sub:'—',progress:'20%',count:'1 / 5 阶段',items:[['未接通','自动联系','第2次 +2小时','状态 → 跟进中 · 已联系；跟进次数 +1'],['已沟通-有意向','确认意向车型','承诺时间或 +2小时 / 次日10:00','确认意向车型，进入购车引导'],['已沟通-无意向','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 无意向购买'],['要求稍后联系','按客户指定时间回访','销售录入客户指定时间','状态 → 跟进中 · 已联系'],['号码错误','无动作（终态）','—','状态 → 战败-号码错误'],['已发送预审链接','跟进预审进度','第2次 +2小时；第3次次日10:00','状态 → 跟进中 · 已联系']]},
  following:{main:'跟进中',sub:'已联系',progress:'40%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系状态流转','按联系节奏','状态保持 跟进中 · 已联系'],['已发送预审链接','跟进预审进度','第2次 +2小时；第3次次日10:00','直接触发复制链接动作'],['试驾','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 试驾'],['已沟通-无意向','转低频唤醒','+30天唤醒一次','状态 → 暂存 · 无意向购买'],['未接通（第2次）','重新联系','第3次次日10:00','状态不变；跟进次数 +1（累计2）'],['未接通（第3次，达上限）','无动作','—','系统自动 → 战败（原因：未接通）'],['要求稍后联系','按客户指定时间回访','销售录入客户指定时间','状态不变'],['预审通过','进入订单流程','—','状态 → 订单中-预审通过'],['放弃购买','无动作（终态）','—','状态 → 战败（原因：暂时不买）']]},
  order:{main:'订单中',sub:'预审通过',progress:'70%',count:'4 / 5 阶段',items:[['待客户进件','联系用户，提醒协助提交进件材料','预审通过后+2小时；先+1天、+3天','状态保持 订单中'],['等待信审结果','主动查询订单状态','+1 / +3 / +7天','状态保持 订单中'],['报价待确认','推动客户确认金融报价方案','进入后+1天首跟，未完成每+1天','状态保持 订单中'],['合同待签署','协助客户确认/签署合同','进入后+1天首跟，未完成每+1天','状态保持 订单中'],['等待放款','跟进放款进度，需找 Mstar 查询','进入后+1天首跟，未完成每+1天','状态保持 订单中']]},
  testdrive:{main:'暂存',sub:'试驾',progress:'45%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  cash:{main:'暂存',sub:'确认全款',progress:'55%',count:'3 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（未达上限）','重新联系','第2次 +2小时；第3次次日10:00','状态不变；重试次数 +1'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  'no-intent':{main:'暂存',sub:'无意向购买',progress:'35%',count:'2 / 5 阶段',items:[['已沟通-有意向','进入已联系的状态流转','按联系节奏','状态 → 跟进中 · 已联系'],['未接通（未达上限）','重新联系','第2次 +2小时；第3次次日10:00','状态不变；重试次数 +1'],['未接通（达上限）','无动作','—','系统按次数自动判定为战败']]},
  lost:{main:'战败',sub:'—',progress:'100%',count:'终态',items:[['战败','无后续动作','—','原因：号码错误 / 放弃购买 / 预审失败 / 未接通电话']]}
};
function renderLeadState(key){
  updateTaskContext(key);
  const isOrder=key==='order';document.querySelector('.stage-list').classList.toggle('hidden',isOrder);document.querySelector('.form-label-title').classList.toggle('hidden',isOrder);document.querySelector('.form-row').classList.toggle('hidden',isOrder);$('#orderModeNotice').classList.toggle('hidden',!isOrder);document.querySelector('.form-row input').required=!isOrder&&key!=='lost';
  const data=leadStates[key]; $('#currentMainState').textContent=data.main; $('#currentSubState').textContent=data.sub; $('#lostReasonWrap').classList.toggle('hidden', key !== 'lost');
  const list=$('#stageList'); list.innerHTML=data.items.map((x,i)=>`<button class="stage ${i===0?'selected':''}" data-stage="${x[0]}" data-action="${x[3]}" data-next="${x[2]}"><span class="stage-radio"></span><b>${x[0]}</b><small>${x[1]}</small><time>${x[2]}</time></button>`).join(''); bindStages(); const first=data.items[0]; $('#autoAction').textContent=first[3]; $('#nextAction').textContent=first[2];
}
function bindStages(){document.querySelectorAll('.stage').forEach(stage=>stage.addEventListener('click',()=>{document.querySelectorAll('.stage').forEach(s=>s.classList.remove('selected'));stage.classList.add('selected');$('#autoAction').textContent=stage.dataset.action;$('#nextAction').textContent=stage.dataset.next;}));}
$('#leadStateSelect').addEventListener('change',e=>renderLeadState(e.target.value)); $('#leadStateSelect').value='following'; renderLeadState('following');
document.querySelector('.identity-card .text-btn').addEventListener('click',()=>$('#userInfoModal').classList.remove('hidden'));
$('#closeUserModal').addEventListener('click',()=>$('#userInfoModal').classList.add('hidden'));
document.querySelectorAll('.info-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.info-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');['current','original','history'].forEach(k=>$('#'+k+'InfoPanel').classList.toggle('hidden',k!==tab.dataset.infoTab));}));
$('#saveUserInfo').addEventListener('click',()=>{const map={currentLeadType:$('#editType').value,currentPhone:$('#editPhone').value,currentBrand:$('#editBrand').value,currentSeries:$('#editSeries').value,currentModel:$('#editModel').value,currentDealer:$('#editDealer').value,currentAddress:$('#editAddress').value,currentRegion:$('#editRegion').value};Object.entries(map).forEach(([id,value])=>$('#'+id).textContent=value||'—');const reason=$('#editReason').value.trim()||'销售手动更新用户信息';$('#changeList').innerHTML=`<div class="change-item"><time>刚刚 · Sofia Ramirez</time><p>${escapeHtml(reason)}</p><small>当前信息已更新，原始线索快照保持不变</small></div>`;$('#userInfoModal').classList.add('hidden');showToast('当前用户信息已保存，原始信息已保留');});

$('#addNoteBtn').addEventListener('click', () => { $('#noteForm').classList.remove('hidden'); $('#noteInput').focus(); });
$('#cancelNote').addEventListener('click', () => { $('#noteForm').classList.add('hidden'); $('#noteInput').value = ''; });
$('#noteForm').addEventListener('submit', (e) => {
  e.preventDefault();
  const text = $('#noteInput').value.trim(); if (!text) return;
  const item = document.createElement('div'); item.className = 'timeline-item';
  item.innerHTML = `<span class="timeline-dot purple"></span><div><div class="timeline-head"><time>刚刚</time></div><p>${escapeHtml(text)}</p><div class="operator-line">操作人：sales 001 Deng Yao</div></div>`;
  $('#noteTimeline').prepend(item); $('#noteForm').classList.add('hidden'); $('#noteInput').value = '';
  $('#noteCount').textContent = Number($('#noteCount').textContent) + 1; showToast('跟踪记事已保存');
});
$('#precheckBtn').addEventListener('click', () => $('#precheckModal').classList.remove('hidden'));
$('#closePrecheck').addEventListener('click', () => $('#precheckModal').classList.add('hidden'));
$('#precheckModal').addEventListener('click', e => { if(e.target.id === 'precheckModal') e.currentTarget.classList.add('hidden'); });
$('#savePrecheck').addEventListener('click', () => showToast('预审信息已保存'));
$('#startAttribution').addEventListener('click', () => showToast('归因链接已发起'));
$('#favoriteBtn').addEventListener('click', () => { const b = $('#favoriteBtn'); b.classList.toggle('active'); b.textContent = b.classList.contains('active') ? '★ 已收藏' : '☆ 收藏'; showToast(b.classList.contains('active') ? '已加入收藏' : '已取消收藏'); });
let leadQueue=[];let currentLeadIndex=0;
function renderLeadActivity(lead){$('#currentName').textContent=lead.name;$('#currentPhone').textContent=lead.phone;$('#currentBrand').textContent=lead.brand;$('#currentSeries').textContent=lead.series;$('#currentModel').textContent=lead.model;$('#opsTimeline').innerHTML=`<div class="timeline-item"><span class="timeline-dot gray"></span><div><div class="timeline-head"><b>进入当前工作台</b><time>刚刚</time></div><p>系统根据销售提交结果切换到下一条线索</p><div class="operator-line">操作人：系统</div></div></div><div class="timeline-item"><span class="timeline-dot blue"></span><div><div class="timeline-head"><b>线索已创建</b><time>今天 09:30</time></div><p>来源：系统自动 · 线索中心</p><div class="operator-line">操作人：系统</div></div></div>`;$('#noteTimeline').innerHTML=lead.notes.map((n,i)=>`<div class="timeline-item"><span class="timeline-dot purple"></span><div><div class="timeline-head"><time>${i?'昨天 16:40':'今天 10:18'}</time></div><p>${escapeHtml(n)}</p><div class="operator-line">操作人：sales 001 Deng Yao</div></div></div>`).join('');$('#noteCount').textContent=lead.notes.length;}
function loadNextLead(){currentLeadIndex=(currentLeadIndex+1)%leadQueue.length;const lead=leadQueue[currentLeadIndex];$('#leadStateSelect').value=lead.state;renderLeadState(lead.state);$('#currentMainState').textContent=lead.main;$('#currentSubState').textContent=lead.sub;renderLeadActivity(lead);showToast(`已提交，进入下一条：${lead.name}`);}
$('#completeBtn').addEventListener('click', () => { const state=$('#leadStateSelect').value; if(state!=='order'&&!$('#lostReasonWrap').classList.contains('hidden')&&!$('#lostReason').value){ showToast('请先选择战败原因'); $('#lostReason').focus(); return; } if(state!=='order'&&!$('.form-row input').value){ showToast('请先设置下次跟进时间'); $('.form-row input').focus(); return; } loadNextLead(); });
$('#skipBtn').addEventListener('click',()=>{const reason=window.prompt('请输入跳过原因：','当前不方便联系');if(!reason)return;showToast(`任务已跳过：${reason}，2小时后重新派发`);});
let allLeadRows=[];
function renderLeadRows(){document.querySelector('.lead-table tbody').innerHTML=allLeadRows.map(r=>`<tr><td><span class="table-pill">${r[0]}</span></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>2026-08-05 06:42</td><td>${r[6]}</td><td><button class="table-link" data-open-workbench>查看</button></td></tr>`).join('');document.querySelectorAll('[data-open-workbench]').forEach(btn=>btn.addEventListener('click',()=>{roleSelect.value='sales';setRole('sales');showToast('已进入对应销售工作台');}));}
fetch('./data.json').then(response=>{if(!response.ok)throw new Error('data.json load failed');return response.json();}).then(data=>{leadQueue=data.leads;allLeadRows=data.leadRows;renderLeadRows();renderLeadState('following');renderLeadActivity(leadQueue[0]);}).catch(()=>showToast('演示数据加载失败，请确认 data.json 已上传'));
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
$('#changeList').innerHTML='<div class="change-item"><time>今天 10:18 · Sofia Ramirez</time><p><b>车型</b>：3 Sedan → I GRAND TOURING MHEV TA</p><small>修改原因：客户电话确认最终意向车型</small></div><div class="change-item"><time>昨天 16:42 · Sofia Ramirez</time><p><b>地址</b>：Av. Vallarta 1200 → Av. Vallarta 1410</p><small>修改原因：客户补充完整门牌号</small></div><div class="change-item"><time>07-21 11:05 · 系统同步</time><p><b>地区</b>：Ciudad de México → Ciudad de México · CDMX</p><small>修改原因：根据经销商区域信息自动补全</small></div>';
const currentDemo={currentLeadType:'全款',currentPhone:'5899022435',currentBrand:'长安',currentSeries:'CS75 PLUS',currentModel:'1.5T 尊贵型',currentDealer:'Changan Polanco Centro',currentAddress:'Av. Vallarta 1410',currentRegion:'Guadalajara · JAL'};Object.entries(currentDemo).forEach(([id,value])=>{const el=$('#'+id);if(el)el.textContent=value;});const editDemo={editType:'全款',editPhone:'5899022435',editBrand:'长安',editSeries:'CS75 PLUS',editModel:'1.5T 尊贵型',editDealer:'Changan Polanco Centro',editAddress:'Av. Vallarta 1410',editRegion:'Guadalajara · JAL'};Object.entries(editDemo).forEach(([id,value])=>{const el=$('#'+id);if(el)el.value=value;});
document.querySelectorAll('.note-meta span:first-child').forEach(el=>{el.textContent='操作人：sales 001 Deng Yao';});
